---
- name: installing os centric piece first
  include: "os_family/{{ ansible_os_family }}.yml"

- name: install fisherman
  become: yes
  become_user: "{{ user.name }}"
  get_url:
    url="git.io/fisherman"
    dest="{{ user.home }}/.config/fish/functions/fisher.fish"
    state=present

- name: install bass
  become: yes
  become_user: "{{ user.name }}"
  command: /usr/bin/fish -c 'fisher eds/bass'


- name: change the shell to fish
  user:
    name="{{ user.name }}"
    shell=/usr/bin/fish
